---
title: "BotanizeR tutorial"
author: "Patrick Weigelt"
date: "`r Sys.Date()`"
output: 
  html_vignette:
    toc: true
    toc_depth: 2
    number_sections: true
vignette: >
 %\VignetteIndexEntry{Tutorial for BotanizeR R package}
 %\VignetteEncoding{UTF-8} 
 %\VignetteEngine{knitr::rmarkdown}
editor_options: 
 chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 8)
# Packages --------------------------------------------------------------------
suppressPackageStartupMessages({
  suppressWarnings({
    library(dplyr)
  })
})

options(tinytex.verbose = TRUE)

#devtools::load_all()
```


# 1. Overview

BotanizeR.

\newpage

# 2. Main function
## 2.1. BotanizeR_quiz
Main function to run the script

```{r credentials, eval=FALSE}
library(devtools)
install_github("https://github.com/patrickweigelt/BotanizeR")

library(BotanizeR)

# Species list for Germany with IDs from floraweb.de
data(floraweb_species)

# subset for nearly 200 species forestry students in Göttingen learn.
floraweb_species <- floraweb_species[which(floraweb_species$SUMMER==1),]

# Type in species name, or press enter for next hint or type "skip" and press 
# enter for next species or type "exit" to end quiz and save results
floraweb_species_trained <- BotanizeR_quiz(species_list = floraweb_species, 
                                           hints = c("image","image2","description","status",
                                                     "habitat","family","German name"))
```

